apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ include "netmaker.fullname" . }}-ui
  name: {{ include "netmaker.fullname" . }}-ui
spec:
  replicas: {{ .Values.ui.replicas }}
  selector:
    matchLabels:
      app: {{ include "netmaker.fullname" . }}-ui
  template:
    metadata:
      labels:
        app: {{ include "netmaker.fullname" . }}-ui
    spec:
      containers:
      - name: {{ include "netmaker.fullname" . }}-ui
        image: gravitl/netmaker-ui:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.uiPort }}
        env:
        - name: BACKEND_URL
          {{- if .Values.ingress.enabled }}
          value: 'https://{{ .Values.ingress.hostPrefix.rest }}{{ required "A valid .Values.baseDomain entry required!" .Values.baseDomain}}'
          {{- else }
          value: 'http://{{ include "netmaker.fullname" . }}-rest.{{ .Release.Namespace }}.{{ .Values.service.kubernetesServiceDomain }}:{{ .Values.service.restPort }}'
          {{- end }}}
      terminationGracePeriodSeconds: 15
